### ISSUE TITLE
Authorization error

### ISSUE THREAD

**Issue by flic** [Joolee/nl.joolee.homey.neato#8]
Hi.

I'm getting "Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method." when I try to authorize access to Neato account. Have you seen that error before?

URL: https://apps.neatorobotics.com/oauth2/authorize?client_id=undefined&scope=control_robots+public_profile&response_type=code&redirect_uri=https://callback.athom.com/oauth2/callback/

Homey Firmware v1.0.1

**Comment by Joolee** [comment]
Yup, that's to be expected for now. You need to register an application as Neato developer. When you do this, you'll get some secret codes to identify your application. As they should remain secret, we do not include them in the repo. :P We can include our secret parameters when we upload the app to the Homey store.

In the mean time, you can register your own application here:
https://developers.neatorobotics.com/applications
Use this as redirect url: https://callback.athom.com/oauth2/callback/
Select both scopes ( public_profile and control_robots )
Make up the rest yourself :)

Next, create a file called env.json next to app.json in the root folder of the app with the following content:
```
{
    "CLIENT_ID": "<Client ID>",
    "CLIENT_SECRET": "<Secret>"
}
```
Replace `<Client ID>` and `<Secret>` with the strings you got from Neato.

**Comment by flic** [comment]
Thanks!
